services:
  app:
    build: ./typescript-app
    container_name: ts_app
    ports:
     - 3000:3000
    volumes:
     - ./typescript-app:/app
     - /app/node_modules/
    stdin_open: true
    tty: true